import { Module } from '@nestjs/common';
import { SequelizeModule } from '@nestjs/sequelize';
import {
  ActivityLogModel,
  ActivityLogUserModel,
  ChoiceModel,
  ConfigExamModel,
  ConfigExamPaperModel,
  ConfigModel,
  CreditModel,
  ExamineeGroupModel,
  ExamineeModel,
  ExamineesGroupExamPaperModel,
  ExamModel,
  ExamPaperModel,
  ExamPaperTagModel,
  ExamTagModel,
  FileUploadModel,
  InstitutionModel,
  InstitutionUserModel,
  InstructionModel,
  JobTitleModel,
  MpesaStkRequestModel,
  NotificationModel,
  NotificationUserModel,
  OtpModel,
  PasswordResetModel,
  PaymentModel,
  PermissionModel,
  PlanInfoModel,
  PlanModel,
  QuestionModel,
  QuestionTagModel,
  QuoteModel,
  RoleModel,
  RoleUserModel,
  SettingModel,
  TagModel,
  TransactionModel,
  UserModel,
} from './models';
import { dbConfig } from './config/db.config';

@Module({
  imports: [
    SequelizeModule.forRoot({
      ...dbConfig,
      logging: false,
      models: [
        PermissionModel,
        RoleModel,
        UserModel,
        RoleUserModel,
        FileUploadModel,
        ExamModel,
        TagModel,
        ExamTagModel,
        OtpModel,
        PasswordResetModel,
        ConfigModel,
        ConfigExamModel,
        ExamPaperModel,
        ConfigExamPaperModel,
        ExamPaperTagModel,
        QuestionModel,
        ChoiceModel,
        InstructionModel,
        NotificationModel,
        NotificationUserModel,
        ExamineeGroupModel,
        ExamineeModel,
        InstitutionModel,
        InstitutionUserModel,
        ExamineesGroupExamPaperModel,
        SettingModel,
        MpesaStkRequestModel,
        CreditModel,
        TransactionModel,
        PlanModel,
        PlanInfoModel,
        QuoteModel,
        PaymentModel,
        QuestionTagModel,
        ActivityLogModel,
        ActivityLogUserModel,
        JobTitleModel,
      ],
    }),
  ],
})
export class DbModule {}
